package com.demo.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _ip_pool_MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _ip_pool_MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("ip", "id", Ip.class);
	}
}

