package com.demo.model;

import com.demo.model.base.BaseIp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ip extends BaseIp<Ip> {
	public static final Ip dao = new Ip().dao();
}
